Repository wanted-pre-onboarding-backend-django/feed-flow, pull requests merged in 2024-08, with the labels that each got.

#2 Setting: 개발 환경 설정
  .flake8
  .github/ISSUE_TEMPLATE/custom.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .gitignore
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  README.md
  config/__init__.py
  config/asgi.py
  config/models.py
  config/settings.py
  config/urls.py
  config/wsgi.py
  manage.py
Labels: setup

#13 Fix : setting timezone 변경 및 폴더명 복수화
  .gitignore
  article/serializers/__init__.py
  config/settings.py
Labels: bug

#14 Feat: 게시물 좋아요 기능 구현
  article/migrations/0002_article_title.py
  article/urls.py
  article/views/__init__.py
  article/views/article_like_views.py
Labels: develop, feat

#15 Feat: articles crud
  article/admin/__init__.py
  article/admin/article_admin.py
  article/serializers/__init__.py
  article/serializers/aricle_detail_serializer.py
  article/serializers/article_list_serializer.py
  article/urls.py
  article/views/__init__.py
  article/views/article_detail_view.py
  article/views/article_list_view.py
  user/admin/__init__.py
  user/admin/user_admin.py
  user/serializers/__init__.py
  user/serializers/tiny_user_serializer.py
Labels: feat

#17 Feat: 게시글 테스트 위한 유저모델 커스텀화
  .flake8
  article/migrations/0001_initial.py
  article/migrations/0002_article_title.py
  article/migrations/0002_initial.py
  config/settings.py
  user/migrations/0001_initial.py
  user/models.py
Labels: feat

#20 Test: 게시물 좋아요 & 공유 기능 test 코드 작성
  article/tests.py
  article/tests/__init__.py
  article/tests/test_article_like.py
  article/tests/test_article_share.py
  article/views/article_like_views.py
  article/views/article_share_view.py
  config/settings.py
Labels: test

#24 Feat: 게시물 리스트 쿼리파라미터 구현
  article/serializers/article_list_serializer.py
  article/views/article_detail_view.py
  article/views/article_list_view.py
Labels: feat

#25 Feat: 게시물의 해시태그 기반 통계 기능 구현
  article/admin/article_admin.py
  article/serializers/__init__.py
  article/serializers/article_statistics_serializer.py
  article/urls.py
  article/views/__init__.py
  article/views/article_statistics_api_view.py
Labels: develop, feat

#30 Setting : Docker & WS & WAS & PostgreSQL 설정
  Dockerfile
  Pipfile
  Pipfile.lock
  config/gunicorn_config.py
  config/settings.py
  docker-compose.yml
  nginx.conf
Labels: setup

#32 Test: 게시물의 통계 기능 test 코드 작성
  article/serializers/article_statistics_serializer.py
  article/tests/__init__.py
  article/tests/test_article_statistics.py
  article/urls.py
  article/views/article_statistics_api_view.py
Labels: test

#34 Docs: readme 작성
  README.md
Labels: test

#35 Feat: 회원가입과 로그인
  Pipfile
  Pipfile.lock
  config/authentication.py
  config/settings.py
  config/urls.py
  user/__init__.py
  user/migrations/0003_user_is_approved.py
  user/models/user.py
  user/serializers/__init__.py
  user/serializers/user_serializer.py
  user/serializers/user_signup_serializer.py
  user/urls.py
  user/views/__init__.py
  user/views/user_change_password_view.py
  user/views/user_login_view.py
  user/views/user_logout_view.py
  user/views/user_me_view.py
  user/views/user_public_view.py
  user/views/user_signup_confirm_view.py
  user/views/user_signup_view.py
Labels: feat

#40 Setting : Docker & server + PostgreSQL 설정
  Dockerfile
  Pipfile
  Pipfile.lock
  config/gunicorn_config.py
  config/settings.py
  docker-compose.yml
  nginx.conf
Labels: setup
